/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.HashSet;
import registroalumno.Alumno;
import registroalumno.Materia;

/**
 *
 * @author Valentin Barros
 */
public class Menu extends javax.swing.JFrame {

    public static HashSet<Alumno> alumnos = new HashSet();
    public static HashSet<Materia> materias = new HashSet();  

   
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public static HashSet<Alumno> getAlumnos() {
        return alumnos;
    }

    public static void setAlumnos(HashSet<Alumno> alumnos) {
        Menu.alumnos = alumnos;
    }

    public static HashSet<Materia> getMaterias() {
        return materias;
    }

    public static void setMaterias(HashSet<Materia> materias) {
        Menu.materias = materias;
    }

    public static void agregarAlumno(Alumno a){
        alumnos.add(a);
    }
    
    public static void agregarMateria(Materia m){
        materias.add(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDPMenuPrincipal = new javax.swing.JDesktopPane();
        jMBMenu = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMIAgregarAlumno = new javax.swing.JMenuItem();
        jMIVerAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMIAgregarMateria = new javax.swing.JMenuItem();
        jMIVerMaterias = new javax.swing.JMenuItem();
        jMRegistro = new javax.swing.JMenu();
        jMIAgregarRegistro = new javax.swing.JMenuItem();
        jMIMateriasInscriptas = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        javax.swing.GroupLayout jDPMenuPrincipalLayout = new javax.swing.GroupLayout(jDPMenuPrincipal);
        jDPMenuPrincipal.setLayout(jDPMenuPrincipalLayout);
        jDPMenuPrincipalLayout.setHorizontalGroup(
            jDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDPMenuPrincipalLayout.setVerticalGroup(
            jDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMBMenu.setToolTipText("Registro de Alumno");

        jMAlumno.setText("Alumno");

        jMIAgregarAlumno.setText("Agregar alumno");
        jMIAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIAgregarAlumno);

        jMIVerAlumno.setText("Ver Alumnos");
        jMIVerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVerAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIVerAlumno);

        jMBMenu.add(jMAlumno);

        jMMateria.setText("Materia");

        jMIAgregarMateria.setText("Agregar materia");
        jMIAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMIAgregarMateria);

        jMIVerMaterias.setText("Ver Materias");
        jMIVerMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVerMateriasActionPerformed(evt);
            }
        });
        jMMateria.add(jMIVerMaterias);

        jMBMenu.add(jMMateria);

        jMRegistro.setText("Registro");

        jMIAgregarRegistro.setText("Formulario Inscripcion");
        jMIAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarRegistroActionPerformed(evt);
            }
        });
        jMRegistro.add(jMIAgregarRegistro);

        jMIMateriasInscriptas.setText("Materias Inscriptas");
        jMIMateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMateriasInscriptasActionPerformed(evt);
            }
        });
        jMRegistro.add(jMIMateriasInscriptas);

        jMBMenu.add(jMRegistro);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });

        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMSalir.add(jMISalir);

        jMBMenu.add(jMSalir);

        setJMenuBar(jMBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenuPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        FormularioAlumno form = new FormularioAlumno();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIAgregarAlumnoActionPerformed

    private void jMIAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarMateriaActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        FormularioDeMaterias form = new FormularioDeMaterias();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIAgregarMateriaActionPerformed

    private void jMIAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarRegistroActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        FormularioDeInscripcion form = new FormularioDeInscripcion();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIAgregarRegistroActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMIVerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVerAlumnoActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        AlumnosInscriptos form = new AlumnosInscriptos();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIVerAlumnoActionPerformed

    private void jMIVerMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVerMateriasActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        MateriasExistentes form = new MateriasExistentes();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIVerMateriasActionPerformed

    private void jMIMateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMateriasInscriptasActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        MateriasInscriptas form = new MateriasInscriptas();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIMateriasInscriptasActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMISalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPMenuPrincipal;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenuItem jMIAgregarAlumno;
    private javax.swing.JMenuItem jMIAgregarMateria;
    private javax.swing.JMenuItem jMIAgregarRegistro;
    private javax.swing.JMenuItem jMIMateriasInscriptas;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenuItem jMIVerAlumno;
    private javax.swing.JMenuItem jMIVerMaterias;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMRegistro;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
