/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Valentin Barros
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPMenuPrincipal = new javax.swing.JDesktopPane();
        jMBMenu = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMIAgregarAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMIAgregarMateria = new javax.swing.JMenuItem();
        jMRegistro = new javax.swing.JMenu();
        jMIAgregarRegistro = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        javax.swing.GroupLayout jDPMenuPrincipalLayout = new javax.swing.GroupLayout(jDPMenuPrincipal);
        jDPMenuPrincipal.setLayout(jDPMenuPrincipalLayout);
        jDPMenuPrincipalLayout.setHorizontalGroup(
            jDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDPMenuPrincipalLayout.setVerticalGroup(
            jDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMBMenu.setToolTipText("Registro de Alumno");

        jMAlumno.setText("Alumno");

        jMIAgregarAlumno.setText("Agregar alumno");
        jMIAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIAgregarAlumno);

        jMBMenu.add(jMAlumno);

        jMMateria.setText("Materia");

        jMIAgregarMateria.setText("Agregar materia");
        jMIAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMIAgregarMateria);

        jMBMenu.add(jMMateria);

        jMRegistro.setText("Registro");

        jMIAgregarRegistro.setText("Formulario Inscripcion");
        jMIAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarRegistroActionPerformed(evt);
            }
        });
        jMRegistro.add(jMIAgregarRegistro);

        jMBMenu.add(jMRegistro);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMBMenu.add(jMSalir);

        setJMenuBar(jMBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenuPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        FormularioAlumno form = new FormularioAlumno();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIAgregarAlumnoActionPerformed

    private void jMIAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarMateriaActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        FormularioDeMaterias form = new FormularioDeMaterias();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIAgregarMateriaActionPerformed

    private void jMIAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarRegistroActionPerformed
        // TODO add your handling code here:
        jDPMenuPrincipal.removeAll();
        jDPMenuPrincipal.repaint();
        FormularioDeInscripcion form = new FormularioDeInscripcion();
        form.setVisible(true);
        jDPMenuPrincipal.add(form);
        jDPMenuPrincipal.moveToFront(form);
    }//GEN-LAST:event_jMIAgregarRegistroActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPMenuPrincipal;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenuItem jMIAgregarAlumno;
    private javax.swing.JMenuItem jMIAgregarMateria;
    private javax.swing.JMenuItem jMIAgregarRegistro;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMRegistro;
    private javax.swing.JMenu jMSalir;
    // End of variables declaration//GEN-END:variables
}
